languag: java
jdk:
    - openjdk8

branches:
    only:
        - master

before_install:
    - chmod +x gradlew

# Travis CI 서버의 Home
cache:
    directories:
        - '$HOME/.m2/repository'
        - '$HOME/.gradle'

script: "./gradlew clean build"


before_deploy:
    - zip -r guangju-springboot2-webservice
    - mkdir -p deploy
    - mv guangju-springboot2-webservice.zip deploy/guangju-springboot2-webservice.zip

deploy:
    - provider: s3
      access_key_id: AKIAR7ETQYHBCJIUFNDU #$AWS_ACCESS_KEY # Travis repo settings에 설정된 값

      secret_access_key: 54WAn3S+JLcgS1XekB5/yWZZlUGci/2CFUkdP4MR #$AWS_SECRET_KEY # Travis repo settings에 설정된 값

      bucket: guangju-springboot-build # S3 버킷
      region: ap-northeast-2
      skip_cleanup: true
      acl: private # zip 파일 접근을 private으로
      local_dir: deploy # before_deploy에서 생성한 디렉토리
      wait-until-deployed: true


# CI 실행 완료 시 메일로 알람
notifications:
    email:
        recipients:
            - wnghks517@gmail.com